@WebAPI_Demo.API_HostAddress = http://localhost:5012

GET http://localhost:5012/persons/
Accept: application/json

###

GET http://localhost:5012/phones/
Accept: application/json

###

GET http://localhost:5012/person/810b4e45-11b0-4601-8227-3830f5626732
Accept: application/json

### 

GET http://localhost:5012/person/1
Accept: application/json

### 